name: 'Comment Progress'
description: 'Posts progress comments to Meshery Cloud PR'
inputs:
  github-token:
    description: 'GitHub token for authentication'
    required: true
  pr_number:
    description: 'Pull request number'
    required: true
  message:
    description: 'Message to post'
    required: true
  append:
    description: 'Whether to append to existing comment'
    required: false
    default: 'true'
  recreate:
    description: 'Whether to recreate the comment'
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: Post comment
      uses: hasura/comment-progress@v2.3.0
      with:
        github-token: ${{ inputs.github-token }}
        repository: "layer5io/meshery-cloud"
        number: ${{ inputs.pr_number }}
        id: meshery-cloud
        message: ${{ inputs.message }}
        append: ${{ inputs.append }}
        recreate: ${{ inputs.recreate }}
