name: Build and Deploy Site

on:
  push:
    branches: [ master ]
    paths:
      - 'site/**'
  workflow_dispatch:
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          sparse-checkout: |
            Makefile
            install
            site
            github-pages-deploy-action-temp-deployment-folder
          sparse-checkout-cone-mode: false
      - name: Install and Build 🔧 
        run: |
          mkdir /home/runner/work/meshery-extensions-packages/meshery-extensions-packages/github-pages-deploy-action-temp-deployment-folder
          make setup
          make build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: site # The branch the action should deploy to.
          folder: site/public # The folder the action should deploy.
          clean: true
