name: Meshery Cloud Build Reusable
on:
  workflow_call:
    inputs:
      pr_commit_sha:
        required: true
        type: string
      pr_number:
        required: true
        type: string
    secrets:
      PROVIDER_TOKEN:
        required: true
      NODE_VERSION:
        required: true
      GO_VERSION:
        required: true
      GH_ACCESS_TOKEN:
        required: true
      CYPRESS_RECORD_KEY:
        required: true
      LAYER5_CLOUD_USERNAME:
        required: true
      LAYER5_CLOUD_PASSWORD:
        required: true
      LAYER5_CLOUD_TESTING_BOT_EMAIL:
        required: true
      LAYER5_CLOUD_TESTING_BOT_PASSWORD:
        required: true
jobs:
  comment-starting-point:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout for composite action
        uses: actions/checkout@v4
      - name: comment starting point
        uses: ./.github/actions/comment-progress
        with:
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
          pr_number: ${{ inputs.pr_number }}
          message: "Starting [Cloud Server Build](https://github.com/layer5labs/meshery-extensions-packages/actions/runs/${{ github.run_id }})..."
          recreate: true
  build-meshery-cloud:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Checkout Cloud code
        uses: actions/checkout@v4
        with:
          repository: "layer5io/meshery-cloud"
          path: ./meshery-cloud
          fetch-depth: 1
          ref: ${{ inputs.pr_commit_sha }}
          token: ${{ secrets.GH_ACCESS_TOKEN }}
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ secrets.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: 'meshery-cloud/ui/package-lock.json'
      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"


      - name: Install Cloud UI dependencies
        working-directory: ./meshery-cloud
        run: make ui-setup
      - name: Install Redocly, Prettier, and ESLint
        working-directory: ./meshery-cloud
        run: |
          npm i -g @redocly/cli@latest
          npm i -g prettier
          npm i -g eslint
      - name: comment success
        if: success()
        uses: ./.github/actions/comment-progress
        with:
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
          pr_number: ${{ inputs.pr_number }}
          message: ":heavy_check_mark: Cloud UI installing deps complete."
      - name: comment failure
        if: failure()
        uses: ./.github/actions/comment-progress
        with:
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
          pr_number: ${{ inputs.pr_number }}
          message: ":x: Cloud UI installing deps failed."
      
      
      - name: Build Cloud UI
        working-directory: ./meshery-cloud
        run: make ui-build
      - name: comment success
        if: success()
        uses: ./.github/actions/comment-progress
        with:
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
          pr_number: ${{ inputs.pr_number }}
          message: ":heavy_check_mark: Cloud Server UI build complete."
      - name: comment failure
        if: failure()
        uses: ./.github/actions/comment-progress
        with:
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
          pr_number: ${{ inputs.pr_number }}
          message: ":x: Cloud Server UI build failed."
      - name: Validate Meshery Cloud API
        working-directory: ./meshery-cloud
        run: make api-validate-redocly
      - name: comment success
        if: success()
        uses: ./.github/actions/comment-progress
        with:
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
          pr_number: ${{ inputs.pr_number }}
          message: ":heavy_check_mark: Meshery Cloud API validation complete."
      - name: comment Failure
        if: failure()
        uses: ./.github/actions/comment-progress
        with:
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
          pr_number: ${{ inputs.pr_number }}
          message: ":x: Meshery Cloud API validation failed."

      # - name: Lint UI and Backend and apply fixes
      #   run: |
      #     cd meshery-cloud
      #     make ui-lint-fix
      #     make cloud-lint-fix
      # - name: Commit Changes
      #   uses: stefanzweifel/git-auto-commit-action@v5
      #   with:
      #     commit_user_name: l5io
      #     commit_user_email: l5io@layer5.io
      #     commit_author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
      #     commit_options: '--signoff'
      #     commit_message: '[CI] Lint fix backend/ui'
      #     repository: meshery-cloud      
      - name: Build Cloud Server
        working-directory: ./meshery-cloud
        run: |
          make server
      - name: comment success
        if: success()
        uses: ./.github/actions/comment-progress
        with:
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
          pr_number: ${{ inputs.pr_number }}
          message: ":heavy_check_mark: Cloud Server build complete."
      - name: comment Failure
        if: failure()
        uses: ./.github/actions/comment-progress
        with:
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
          pr_number: ${{ inputs.pr_number }}
          message: ":x: Cloud Server build failed."

