name: Meshery Cloud Build On PR Dispatch
on:
  workflow_call:
    inputs:
      pr_commit_sha:
        required: true
        type: string
      pr_number:
        required: true
        type: string
    secrets:
      PROVIDER_TOKEN:
        required: true
      NODE_VERSION:
        required: true
      GO_VERSION:
        required: true
      GH_ACCESS_TOKEN:
        required: true
      CYPRESS_RECORD_KEY:
        required: true
      LAYER5_CLOUD_USERNAME:
        required: true
      LAYER5_CLOUD_PASSWORD:
        required: true
      LAYER5_CLOUD_TESTING_BOT_EMAIL:
        required: true
      LAYER5_CLOUD_TESTING_BOT_PASSWORD:
        required: true
jobs:
  comment-starting-point:
    runs-on: ubuntu-24.04
    steps:
      - name: comment starting point
        uses: hasura/comment-progress@v2.3.0
        with:
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
          repository: "layer5io/meshery-cloud"
          number: ${{ inputs.pr_number }}
          id: meshery-cloud
          message: "Starting [Meshery Cloud Build](https://github.com/layer5labs/meshery-extensions-packages/actions/runs/${{ github.run_id }})..."
          recreate: true
  build-meshery-cloud:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Meshery Cloud code
        uses: actions/checkout@v4
        with:
          repository: "layer5io/meshery-cloud"
          path: ./meshery-cloud
          fetch-depth: 1
          ref: ${{ inputs.pr_commit_sha }}
          token: ${{ secrets.GH_ACCESS_TOKEN }}
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ secrets.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: 'meshery-cloud/ui/package-lock.json'
      - name: Install Cloud UI dependencies
        working-directory: ./meshery-cloud
        run: make ui-setup
      - name: Install Redocly CLI
        working-directory: ./meshery-cloud
        run: npm i -g @redocly/cli@latest
      - name: comment success
        if: success()
        uses: hasura/comment-progress@v2.3.0
        with:
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
          repository: "layer5io/meshery-cloud"
          number: ${{ inputs.pr_number }}
          id: meshery-cloud
          message: ":heavy_check_mark: Meshery Cloud UI installing deps complete."
          append: true
      - name: comment Failure
        if: failure()
        uses: hasura/comment-progress@v2.3.0
        with:
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
          repository: "layer5io/meshery-cloud"
          number: ${{ inputs.pr_number }}
          id: meshery-cloud
          message: ":x: Meshery Cloud UI installing deps Failed."
          append: true
      - name: Build Meshery Cloud UI
        working-directory: ./meshery-cloud
        run: make ui-build
      - name: comment success
        if: success()
        uses: hasura/comment-progress@v2.3.0
        with:
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
          repository: "layer5io/meshery-cloud"
          number: ${{ inputs.pr_number }}
          id: meshery-cloud
          message: ":heavy_check_mark: Meshery Cloud UI build complete."
          append: true
      - name: comment Failure
        if: failure()
        uses: hasura/comment-progress@v2.3.0
        with:
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
          repository: "layer5io/meshery-cloud"
          number: ${{ inputs.pr_number }}
          id: meshery-cloud
          message: ":x: Meshery Cloud UI build Failed."
          append: true
      - name: Validate Meshery Cloud API
        working-directory: ./meshery-cloud
        run: make api-validate-redocly
      - name: comment success
        if: success()
        uses: hasura/comment-progress@v2.3.0
        with:
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
          repository: "layer5io/meshery-cloud"
          number: ${{ inputs.pr_number }}
          id: meshery-cloud
          message: ":heavy_check_mark: Meshery Cloud API Validation complete."
          append: true
      - name: comment Failure
        if: failure()
        uses: hasura/comment-progress@v2.3.0
        with:
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
          repository: "layer5io/meshery-cloud"
          number: ${{ inputs.pr_number }}
          id: meshery-cloud
          message: ":x: Meshery Cloud API Validation Failed."
          append: true